version: 0.2

phases:
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - aws --version
            - aws ecr get-login-password --region eu-west-1 --profile golld | docker login --username AWS --password-stdin 057580831869.dkr.ecr.eu-west-1.amazonaws.com
            - REPOSITORY_URI=057580831869.dkr.ecr.eu-west-1.amazonaws.com/cdk-hnb659fds-container-assets-057580831869-eu-west-1
            - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
            - IMAGE_TAG=${COMMIT_HASH:=latest}
            - echo Getting environment files from S3...
            - aws s3 sync s3://instant-services-metadata/backend .
    build:
        commands:
            - echo Build started on `date`
            - echo Building the Docker image...
            - docker build -t $REPOSITORY_URI:latest .
            - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker images...
            - docker push $REPOSITORY_URI:latest
            - docker push $REPOSITORY_URI:$IMAGE_TAG
            - echo Writing image definitions file...
            - printf '[{"name":"api","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
